modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/SignPicture/SignPicture-Rebornified/issues"

[[mods]]
modId="signpicture"
version="1.0.0"
displayName="SignPicture-Rebornified"
authors="SignPicture Team"
description='''A Minecraft mod that allows players to display images on signs'''

[[mixins]]
config="signpicture.mixins.json"

[[dependencies.signpicture]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.signpicture]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"